
version: '3.8'

services:
  backend:
    image: valenpy22/confites-backend
    ports:
      - "8080:8080"
    depends_on:
      - db


  frontend:
    image: valenpy22/confites-frontend
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdtutorial
      MYSQL_USER: datpy
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
